name: Deployment
on: 
  workflow_dispatch:
  push:
    branches: main
    paths-ignore: './github/workflows/*'
env:
  PORT: ${{ secrets.PORT }}
  MYSQL_HOSTNAME: ${{ secrets.MYSQL_HOSTNAME }}
  MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
  MYSQL_DB: ${{ secrets.MYSQL_DB }}
  MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
  JWT_KEY: ${{ secrets.JWT_KEY }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  STRIPE_SECRET: ${{ secrets.STRIPE_SECRET }}
defaults: 
    run: 
        working-directory: server
jobs: 
    test:
      environment: Test
      runs-on: macos-latest
      steps: 
        - name: Get code
          uses: actions/checkout@v4
        - name: Setup NodeJS
          uses: actions/setup-node@v4
          with:
            node-version: 20
        - name: Cache dependencies
          uses: actions/cache@v4
          with:
            path: ~/.npm
            key: npm-deps-${{ hashFiles('**/package-lock.json') }}
        - name: Install dependencies
          run: npm ci
    deploy:
      needs: test
      runs-on: macos-latest
      steps:
        - name: Output event
          run: echo "${{ toJson(github.event) }}"