name: Deploy Project
on: [push, workflow_dispatch]
defaults: 
    run: 
        working-directory: server
jobs: 
    deploy:
        runs-on: macos-latest
        steps: 
            - name: Get code
              uses: actions/checkout@v4
            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                node-version: 20
            - name: Install dependencies
              run: npm ci